export const SEARCH_JS = `(()=>{const f=document.querySelector("form"),i=f.querySelector("input[name=q]"),r=document.getElementById("results");let t,c,ime=false;const go=()=>{clearTimeout(t);if(ime)return;const q=i.value.trim();if(!q){c?.abort();r.replaceChildren();return}t=setTimeout(async()=>{c?.abort();c=new AbortController();try{const x=await fetch("/api/search?q="+encodeURIComponent(q),{signal:c.signal,headers:{accept:"text/html"}});if(x.ok)r.innerHTML=await x.text()}catch(e){if(e.name!=="AbortError")r.textContent="검색 실패"}},150)};f.addEventListener("submit",e=>{e.preventDefault();go()});i.addEventListener("input",go);i.addEventListener("compositionstart",()=>ime=true);i.addEventListener("compositionend",()=>{ime=false;go()})})();`;

export const UPLOAD_JS = `(()=>{const f=document.getElementById("upload-form"),c=document.getElementById("upload-console");if(!f||!c)return;const b=f.querySelector("button"),stamp=()=>new Date().toLocaleTimeString(undefined,{hour12:false}),log=(level,message)=>{const line="["+stamp()+"] "+level.padEnd(7)+" "+message;c.append(document.createTextNode(line+"\\n"));c.scrollTop=c.scrollHeight};log("READY","업로드 폼 준비 완료");f.elements.image.addEventListener("change",()=>{const file=f.elements.image.files[0];log("SELECT",file?"파일 선택: "+file.name+" ("+file.type+", "+file.size+" bytes)":"파일 선택 취소")});f.addEventListener("invalid",e=>{log("INVALID",e.target.name+" 필드를 확인하세요")},true);f.addEventListener("submit",async e=>{e.preventDefault();const file=f.elements.image.files[0],description=f.elements.description.value.trim();if(!file){log("ERROR","선택된 이미지가 없습니다");return}const started=performance.now(),requestId=crypto.randomUUID();b.disabled=true;log("START","요청 "+requestId);log("INFO","파일="+file.name+", MIME="+(file.type||"application/octet-stream")+", 크기="+file.size+" bytes");log("INFO","설명 길이="+description.length+"자");try{log("FETCH","POST /api/images 전송 시작");const r=await fetch("/api/images",{method:"POST",headers:{"content-type":file.type||"application/octet-stream","x-original-filename":encodeURIComponent(file.name),"x-description":encodeURIComponent(description),"x-client-request-id":requestId},body:file});log("HTTP",r.status+" "+r.statusText);const raw=await r.text();log("BODY",(raw||"(empty response)").slice(0,2000));let value={};try{value=raw?JSON.parse(raw):{}}catch{throw new Error("응답이 JSON 형식이 아닙니다")}if(!r.ok)throw new Error(typeof value.error==="string"?value.error:"업로드 실패");log("SUCCESS","업로드 완료: id="+String(value.id||"")+", hash="+String(value.hash||""));f.reset()}catch(error){log("ERROR",error instanceof Error?error.message:String(error))}finally{b.disabled=false;log("DONE","총 "+Math.round(performance.now()-started)+"ms")}})})();`;

export const ALL_JS = `(()=>{document.addEventListener("click",async e=>{const b=e.target.closest("button[data-delete]");if(!b||!confirm("삭제할까요?"))return;b.disabled=true;try{const r=await fetch("/api/images/"+encodeURIComponent(b.dataset.delete),{method:"DELETE"});if(!r.ok&&r.status!==202)throw new Error("삭제 실패");b.closest("article")?.remove()}catch(e){b.disabled=false;alert(e.message)}})})();`;

export const DEPLOYMENT_JS = `(()=>{const e=document.getElementById("deployment-info");if(!e)return;fetch("/assets/deployment-info.json",{cache:"no-store",headers:{accept:"application/json"}}).then(r=>{if(!r.ok)throw new Error("deployment metadata unavailable");return r.json()}).then(v=>{if(typeof v.deployedAt!=="string"||typeof v.commitSha!=="string")throw new Error("invalid deployment metadata");const d=new Date(v.deployedAt);if(Number.isNaN(d.getTime()))throw new Error("invalid deployment time");const z=Intl.DateTimeFormat().resolvedOptions().timeZone||"local";const t=new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"medium"}).format(d);const s=v.commitSha.slice(0,7);e.textContent="배포: "+t+" ("+z+") · commit "+s;e.title="배포 시각(UTC): "+v.deployedAt+"\\ncommit: "+v.commitSha}).catch(()=>{e.textContent="배포 정보를 확인할 수 없습니다"})})();`;

export const APP_CSS = `.upload-console{box-sizing:border-box;width:100%;min-height:8rem;max-height:20rem;overflow:auto;margin:.75rem 0;padding:.75rem;border:1px solid #30363d;border-radius:6px;background:#0d1117;color:#c9d1d9;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,"Liberation Mono",monospace;white-space:pre-wrap;overflow-wrap:anywhere}.upload-console:empty::before{content:"업로드 로그 대기 중";color:#8b949e}footer{margin-top:1rem}`;
