<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="[18.0.1]" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="[10.0.1]" />
    <PackageReference Include="xunit.v3" Version="[3.2.2]" />
    <PackageReference Include="xunit.runner.visualstudio" Version="[3.1.5]">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SixLabors.ImageSharp" Version="[3.1.12]" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Meme.Origin/Meme.Origin.csproj" />
  </ItemGroup>
</Project>
